### ISSUE TITLE
Errors during migration from v8 to v10

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1797]
**Description**
During updating from v8 to v10, there were plenty of errors.

**Steps to Reproduce**
1. Install v8
2. Open DevTools console for the extension
3. Update from v8 to v10
4. Check the logs
5. A lot of error:

> Adblocker: Error while processing network request - adblocker not ready yet
> TypeError: options.paused.reduce is not a function
> Error while observing options: TypeError: options.paused.reduce is not a function
> TypeError: options.paused is undefined

![image](https://github.com/user-attachments/assets/79774499-d248-4fb0-ab47-f5370a9ed9ab)
![image](https://github.com/user-attachments/assets/dbfa2ca7-8fba-4f9b-baab-adefdac92053)

https://github.com/user-attachments/assets/2435ced6-eb46-4e23-ae66-7d9ea74d18ba

**Expected results**
There should be no errors when migrating from v8 to v10.

Versions
```
GBE 10.3.17 https://github.com/ghostery/ghostery-extension/pull/1738#issuecomment-2275679665
```

**Comment by GRadziejewski** [comment]
Fixed.
Checked here: https://github.com/ghostery/ghostery-extension/issues/1803

https://github.com/user-attachments/assets/b48fa857-79f0-4cc8-8252-b82fbd41791f
