### PR TITLE
Fix options migration from v8

### LINKED ISSUE #1797: Errors during migration from v8 to v10
**Description**
During updating from v8 to v10, there were plenty of errors.

**Steps to Reproduce**
1. Install v8
2. Open DevTools console for the extension
3. Update from v8 to v10
4. Check the logs
5. A lot of error:

> Adblocker: Error while processing network request - adblocker not ready yet
> TypeError: options.paused.reduce is not a function
> Error while observing options: TypeError: options.paused.reduce is not a function
> TypeError: options.paused is undefined

image
image

https://github.com/user-attachments/assets/2435ced6-eb46-4e23-ae66-7d9ea74d18ba

**Expected results**
There should be no errors when migrating from v8 to v10.

Versions
```
GBE 10.3.17 https://github.com/ghostery/ghostery-extension/pull/1738#issuecomment-2275679665
```

### PR DESCRIPTION
**Pull request by smalluban**
Fixes #1797 #1799 #1800

The core issue was to try to migrate options (in v10), which come from v8 (by not setting `optionsVersion`). As the options from v8 have the latest structure (the function was updated when the options structure has been changing), it should skip that process. 

@GRadziejewski Keep in mind, that when the "update" process is triggered by hand (not by the browser, you can still see errors like `Adblocker not ready yet` - as after updating the extension, the browser trigger immediately `onBeforeRequest` API, which cannot run "that fast", as for the first time, the engines are taken from the disk.

### CODE REVIEW

**Review by chrmod — APPROVED** [review]

**Review by GRadziejewski — COMMENTED** [review]
Tests results: https://github.com/ghostery/ghostery-extension/issues/1803#issuecomment-2283357952
